### ISSUE TITLE
[Doc]Update for SQL-DS-Cache 1.1.1 Release

### ISSUE THREAD

**Issue by HongW2019** [oap-project/sql-ds-cache#136]
We are making docs modification for sql-ds-cache 1.1.1 release, here are several aspects need to be discussed:

1. Do NUMA patch still be needed for sql-ds-cache-1.1.1-spark-3.1.1 ?  

If so, there need to be provided a new NUMA-patch for Spark-3.1.1;          
https://github.com/oap-project/sql-ds-cache/blob/branch-1.1-spark-3.1.1/docs/numa-binding-spark-3.0.0.patch
If not, NUMA-related details will be removed.
https://github.com/oap-project/sql-ds-cache/blob/branch-1.1-spark-3.1.1/docs/User-Guide.md#configuration-for-numa
https://github.com/oap-project/sql-ds-cache/blob/branch-1.1-spark-3.1.1/docs/Advanced-Configuration.md#configuration-for-numa

2. The conda packages to be released only have `arrow-plasma-4.0.0.jar` , but notice there is `0.17.0` version info in pom.xml and `sbin`,  so we need confirm the Arrow version.

**Comment by HongW2019** [comment]
@winningsix  Please help point out the Arrow version in sql-ds-cache-1.1.1, thanks a lot.

**Comment by HongW2019** [comment]
@yao531441 FYI.

**Comment by zhixingheyi-tian** [comment]
@xieqi @jikunshang  You can  leave  some  comments here.

cc @yao531441 

Thanks

**Comment by xieqi** [comment]
For Plasma-based-cache, we still use arrow version 0.17.0 in pom.xml for easy build and point out the user to install the intel arrow 4.0.0 at runtime in the user guide.
