### ISSUE TITLE
Using YARN to start Plasma Service cannot work on Dataproc

### ISSUE THREAD

**Issue by HongW2019** [oap-project/sql-ds-cache#164]
To test plasma-sql-ds-cache on Google Cloud Dataproc, we run TPC-DS 9 queries with plasma-sql-ds-cache  enabled on Google Cloud Dataproc 2.0 (`CentOS 8, Hadoop 3.2.2, Spark 3.1.1`)

When use YARN to start Plasma service,  found Yarn service couldn't start on Dataproc.

![image](https://user-images.githubusercontent.com/30172512/126040368-5c5b9159-7d8e-4603-9085-436c8c495bf7.png)

This is due to Dataproc Yarn default config. Dataproc sets the yarn-site.xml yarn.resourcemanager.webapp.methods-allowed property to "GET,HEAD". which restricts the HTTP methods that can be called on the YARN Resource Manager web UI and REST APIs to the GET and HEAD methods. This default setting also disables job submission and modifications via the YARN REST API.

After deleted this configuration, Plasma-SQL-DS-Cache works on Dataproc clusters.

**Comment by zhixingheyi-tian** [comment]
@HongW2019  
Please add some comments for the close.

**Comment by HongW2019** [comment]
> @HongW2019
> Please add some comments for the close.

@zhixingheyi-tian  Please refer to comment above.

**Comment by zhixingheyi-tian** [comment]
@HongW2019 
You can creation a new cell for description instead of edit in the original cell.

**Comment by HongW2019** [comment]
This is due to Dataproc Yarn default config. Dataproc sets the yarn-site.xml yarn.resourcemanager.webapp.methods-allowed property to "GET,HEAD". which restricts the HTTP methods that can be called on the YARN Resource Manager web UI and REST APIs to the GET and HEAD methods. This default setting also disables job submission and modifications via the YARN REST API.

After deleted this configuration, Plasma-SQL-DS-Cache works on Dataproc clusters.
