### ISSUE TITLE
Upgrade hadoop dependencies in HCFS

### ISSUE THREAD

**Issue by iyupeng** [oap-project/sql-ds-cache#62]
HCFS uses low version of Hadoop libraries.

It should be upgraded since the vulnerabilities in old libraries.

**Comment by jikunshang** [comment]
have cherry-pick this pr to [branch-1.1](597f2604d56008377a9d44754e8f9f91680c9d3a), close this one.

**Comment by HongW2019** [comment]
@iyupeng It turns out that this Hadoop version `3.2.2` still bring some vulnerabilities after scanning, so...could Hadoop be upgraded to the latest version `3.3.0` to minimize the number of issues?

**Comment by HongW2019** [comment]
@iyupeng  There are still many vulnerabilities left after re-scanning on this version, so...could Hadoop be upgraded to latest version `3.3.0` to minimize the number of issues?

**Comment by iyupeng** [comment]
> @iyupeng There are still many vulnerabilities left after re-scanning on this version, so...could Hadoop be upgraded to latest version `3.3.0` to minimize the number of issues?

Yes. It will be upgraded to `3.3.0`. Then you can scan again.

**Comment by jikunshang** [comment]
@HongW2019  Do we need update master branch?

**Comment by HongW2019** [comment]
> @HongW2019 Do we need update master branch?

Yes, please also cherry-pick it to master.

**Comment by jikunshang** [comment]
> > @HongW2019 Do we need update master branch?
> 
> Yes, please also cherry-pick it to master.

Done. Please check again, thanks! I will close this issue if it works.

**Comment by HongW2019** [comment]
> > > @HongW2019 Do we need update master branch?
> > 
> > 
> > Yes, please also cherry-pick it to master.
> 
> Done. Please check again, thanks! I will close this issue if it works.

Yes, you can close this issue, thanks.
